---

api_key: fakekey
galaxy_instance: http://localhost:8080
install_repository_dependencies: true
install_resolver_dependencies: true
install_tool_dependencies: false

tools:
  - name: suite_daiac
    owner: jay
    tool_panel_section_label: "GAIAC Galaxy"